package de.hybris.platform.ruleengine.drools;

import de.hybris.ruleengine.stage.sample.Fibonacci;

rule "${rule_uuid}"
@ruleCode("${rule_code}")
@moduleName("${module_name}")
dialect "mvel" 
salience 10
when
    fibo_nacci : Fibonacci ( value == -1 )
           not ( Fibonacci ( sequence == 1 ) )
then
   insert( new Fibonacci( fibo_nacci.sequence - 1 ) );
           System.out.println( "recurse for " + fibo_nacci.getSequence() );
end
